name: Release Pipeline

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME="your-dockerhub-username/your-repo"
          TAG_NAME="${{ github.event.release.tag_name }}"
          docker build -t $IMAGE_NAME:$TAG_NAME .
          docker push $IMAGE_NAME:$TAG_NAME

